sudo: true
language: java
jdk:
  - oraclejdk8

install: true
before_install:
 - ulimit -c unlimited -S
 - wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
 - unzip -qq apache-maven-3.3.9-bin.zip
 - export M2_HOME=$PWD/apache-maven-3.3.9
 - export PATH=$M2_HOME/bin:$PATH
script: "mvn clean install"
cache:
  directories:
    - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer