sudo: true
language: java
jdk:
  - oraclejdk8
before_install:
  - ulimit -c unlimited -S
after_success:
  - mvn -B cobertura:cobertura coveralls:report
cache:
  directories:
    - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer